import Head from "next/head";
import Header from "../components/Header";
import Features from "../components/Features";
import { server } from "../config";
import Properties from "../components/Properties";

export default function Home({ properties }) {
	return (
		<>
			<Head>
				<title>Home Rental - Home</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Header />
				<Features />
				<Properties properties={properties} />
			</main>
		</>
	);
}

export const getStaticProps = async () => {
	const res = await fetch(`${server}/api/properties`);
	const properties = await res.json();

	return {
		props: {
			properties,
		},
	};
};
