import Head from "next/head";
import Header from "../components/Header";
import Features from "../components/Features";
import Properties from "../components/Properties";
import { properties } from "../data/data";

export default function Home() {
	return (
		<>
			<Head>
				<title>Home Rental - Home</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>
				<Header />
				<Features />
				<Properties properties={properties} />
			</div>
		</>
	);
}
